* Raspberry based playback devices for Sonic Epistemologies

/2016-04, revised 2018-07 rumori/

** Hardware/software setup

Playback to the suspended headphones is realised using Raspberry Pi [fn:1] computers. They are complemented by a switch mechanism and an external USB audio interface, which also allows for a comfortable volume control. The switch is activated by lifting, that is, putting on the headphones such that the suspension strings are untensioned. In idle state, the freely hanging headphones deactivate the switch by their own weight. The switch is connected to one of the Raspberry’s GPIO (General Purpose Input/Outout) ports. 

The playback is controlled by a simple shell script that invokes an instance of =mplayer= on switch activation. After having released the headphone, the =mplayer= process is stopped after a few seconds if still running. Unlike a constantly looping playback, the switch makes sure that each augmented scene is listened to from its beginning when visitors change from one position to the next. 

[fn:1] http://www.raspberrypi.org

** Raspberry setup log

- standard raspbian install via NOOBS 1.9.0
- performed standard apt-get upgrade
- installed extra packages
  + mplayer
  + mg (lightweight emacs-like editor)
+ copied script [[file:sonic_epist.sh]] to raspberry
+ GPIO pins: 15 for playback control, 3 for shutdown/poweroff, active_low:

#+BEGIN_EXAMPLE
Raspberry GPIO (B and later models)

5V  5V  GND 14  15  18  GND 23  24  GND 25  8   7
3V3 2   3   4   GND 17  27  22  3V3 10  9   11  GND

        ^        ^
        poweroff playback
#+END_EXAMPLE

- script argument for indicating scene:

#+BEGIN_EXAMPLE
$ ./sonic_epist.sh A
#+END_EXAMPLE

- for track name body edit =$TRACK= variable in [[file:sonic_epist.sh]]

- autostart via =/etc/rc.local= on raspberry:

#+BEGIN_EXAMPLE
# start installation sonic epistemologies
sudo -u pi -b /home/pi/sonic_epist/hack/sonic_epist.sh [SCENE]
#+END_EXAMPLE

